
version: '3.8'
services:
  lobe-chat:
    image: lobehub/lobe-chat
    container_name: lobe-chat
    ports:
      - "3210:3210"
    environment:
      OPENAI_API_KEY: freeaskinternet
      OPENAI_PROXY_URL: http://freegpt35:3040/v1
      ACCESS_CODE: lobe66
    depends_on:
      - freegpt35
    restart: always
  freegpt35:
    image: missuo/freegpt35:latest
    restart: always
    ports:
      - "3040:3040"
